### ISSUE TITLE
Please update the Icon section in the .desktop file

### ISSUE THREAD

**Issue by guihkx** [NVIDIA/nvidia-settings#13]
Please do not use the absolute path for the nvidia-settings icon. Just use this instead:

`Icon=nvidia-settings`

That way, people like me who use a custom icon theme will get the correct one. More information here:

https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#install_icons
https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#icon_lookup

Thank you.

**Comment by aaronp24** [comment]
I gave this a quick try and gnome-shell wasn't able to find the icon. I'm not sure what I did wrong but I filed internal bug number 2027297 to track this request.

**Comment by GUiHKX** [comment]
That's odd. I just tested it myself on my Arch box also running GNOME 3.26 and it worked immediately after I edited `/usr/share/applications/nvidia-settings.desktop`. If you check the `.desktop` files in `/usr/share/applications/`, you'll notice that none of them uses absolute paths in the `Icon` section.

**Comment by guihkx** [comment]
Hello there @aaronp24, can you please give this one another visit?

The `Icon` section in the desktop file still points to `/usr/share/pixmaps/nvidia-settings.png`, so the program icon for nvidia-settings won't get picked up by the user's current theme.

The links in my first post don't work anymore, so here's updated ones:

* https://developer.gnome.org/desktop-entry-spec/ (Press <kbd>Ctrl</kbd> + <kbd>F</kbd> and search for `Icon`, for the relevant section in the documentation)
* https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#install_icons
* https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#icon_lookup

**Comment by guihkx** [comment]
I posted something but decided to delete. I realized most distros maintain their own .desktop file anyway, so I'm hoping the guys from Arch Linux can fix this in the packaging process.

**Comment by guihkx** [comment]
This was fixed by 51f784cfb23ea48cdf9339a104340993df261f5b. Hooray.
