### ISSUE TITLE
Missing 375.82 release

### ISSUE THREAD

**Issue by jer-gentoo** [NVIDIA/nvidia-settings#15]
375.82 was released in July[1], but there was no accompanying release of nvidia-settings.

[1] http://www.nvidia.com/download/driverResults.aspx/120911/en-us

**Comment by aaronp24** [comment]
Sorry about that. Pushed with commit 24cf945967d3f0b00d9e7a5f1cc7d6385eed7516.

**Comment by jer-gentoo** [comment]
Thank you.
