### ISSUE TITLE
Automate nvidia-settings releases / missing 387.34 release

### ISSUE THREAD

**Issue by jer-gentoo** [NVIDIA/nvidia-settings#18]
At [1] a user requested a 387.34 driver update, but I cannot fulfil that until a matching nvidia-settings release is available.

This is the third time a similar issue is raised, as far as I can tell, so perhaps it is time to automate this?

[1] https://bugs.gentoo.org/638864

**Comment by Manfred-Knick** [comment]
+1
e.g.:

     https://bugs.gentoo.org/618222 :
     nvidia-drivers-381.22:0/381             # missing nvidia-settings-381.22.tar.bz2

**Comment by aaronp24** [comment]
Sorry, I was off for the Thanksgiving break. I'll get to this today.

FWIW, releases appear here first: http://download.nvidia.com/XFree86/nvidia-settings/

**Comment by aaronp24** [comment]
Done with commit 9e8c1f49aaad668a68596af663542f16308dd2ac.
