### ISSUE TITLE
Changes for 396.45 have gtk2 bugs

### ISSUE THREAD

**Issue by mlampe** [NVIDIA/nvidia-settings#27]
![bug](https://user-images.githubusercontent.com/1618953/43344344-aa938388-91e9-11e8-8437-a90761ae7380.png)

Click "Graphics Information". All the new tabs are without a vertical slider and you only see what fits on the tabs:

(nvidia-settings:21224): Gtk-WARNING **: gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead

(nvidia-settings:21224): Gtk-WARNING **: gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead

(nvidia-settings:21224): Gtk-WARNING **: gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead

(nvidia-settings:21224): Gtk-WARNING **: gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead

(nvidia-settings:21224): Gtk-WARNING **: gtk_scrolled_window_add(): cannot add non scrollable widget use gtk_scrolled_window_add_with_viewport() instead

**Comment by aaronp24** [comment]
Thanks for reporting this. We're tracking it with internal bug number 200403459.

**Comment by aaronp24** [comment]
This should have been fixed ages ago and I forgot to close it. Please reopen if you can still reproduce this problem with the latest release.
