### ISSUE TITLE
Digital vibrance/Image Sharpening/ Color Space missing for rtx 2070 in Linux

### ISSUE THREAD

**Issue by positiveinflux** [NVIDIA/nvidia-settings#40]
card rtx 2070 
Asus Rog Strix 2070 Advanced edition
lspci gives;
VGA compatible controller: NVIDIA Corporation Device 1f07 (rev a1)

tried 4 different monitors, several different versions of ubuntu/kubuntu linux mint.
driver used; 
NVIDIA-Linux-x86_64-418.56.run as well as drivers from ppa

It would appear the driver is bugged in monitor detection regardless of what i throw at it, including monitors that work fine in windows 10 regardless of port. Two of the other monitors were able to use digital vibrance fine with a gtx 1050. I also tried adding correct EDID's for each monitor, same result

Would really like to get this resolved since one of the major reasons I bought the rtx 2070 was to not have washed out/dull colors in linux. 

Will provide any additional information.

I originally posted this in linux mint forums as well as devtalk for linux drivers, a forum member recommended me to post it here. Hopefully the bug can be caught and the information is getting in the right hands to resolve it.

**Comment by fabianhjr** [comment]
Similar issue with an ASUS Strix 1070; Color space options appear but is disabled on version 418.74.

**Comment by aaronp24** [comment]
The implementation for digital vibrance changed with the Turing architecture and it wasn't ready in the initial launch drivers. Support for it was added in the [435.17](https://devtalk.nvidia.com/default/topic/1060977/announcements-and-news/-linux-solaris-and-freebsd-driver-435-17-beta-release-/) beta release.  Please give the [435.21](https://devtalk.nvidia.com/default/topic/1062205/announcements-and-news/-linux-solaris-and-freebsd-driver-435-21-short-lived-branch-release-/) official release a try.

If you're still having trouble, please run nvidia-bug-report.sh and send the resulting `nvidia-bug-report.log.gz` file along with a description of the problem to linux-bugs@nvidia.com.

**Comment by fabianhjr** [comment]
No dice

![Screenshot from 2019-09-23 20-32-18](https://user-images.githubusercontent.com/303897/65474423-59a90380-de41-11e9-9ff5-2b5f465fda76.png)
