### ISSUE TITLE
GPULogoBrightness not working on Gigabyte Aorus 1080 Ti

### ISSUE THREAD

**Issue by dustingrady** [NVIDIA/nvidia-settings#41]
Setting the brightness on my GPU has no visual effect, though the command is accepted and shows the updated setting when queried.

```
gish@StarGazer:~$ nvidia-settings -q gpus

1 GPU on StarGazer:0

    [0] StarGazer:0[gpu:0] (GeForce GTX 1080 Ti)

      Has the following names:
        GPU-0
        GPU-69c6c833-8116-b74f-ef7b-31eef4aff471
```

```
gish@StarGazer:~$ nvidia-settings -q gpus

1 GPU on StarGazer:0

    [0] StarGazer:0[gpu:0] (GeForce GTX 1080 Ti)

      Has the following names:
        GPU-0
        GPU-69c6c833-8116-b74f-ef7b-31eef4aff471
```

**Comment by aaronp24** [comment]
This isn't really an nvidia-settings issues. It just queries the available attributes from the driver, which in turn queries this particular setting from the VBIOS. So my guess is that the VBIOS on this GPU has the logo wiring configuration set wrong.

Do the logo brightness settings work in Windows? If so, please run nvidia-bug-report.sh and send the resulting nvidia-bug-report.log.gz file to linux-bugs@nvidia.com.

**Comment by h1z1** [comment]
Kind of funny thing is this DOES WORK with the nouveau driver  and you can do it directly with i2c.
