### ISSUE TITLE
Ubuntu compiling issue.

### ISSUE THREAD

**Issue by leaf918** [NVIDIA/nvidia-settings#7]
Hi,
I spend lot of time on compiling "nvidia-settings" codes.I need to use the api in this to configure and get gpu info,and SDI captures card info.
when this lib is compiled,I got lots of dependence error,such like X11,vulpaud,gtk.
IS THERE a compiled lib ,or HOW TO compile tutorials?
Thanks very much!!

**Comment by aaronp24** [comment]
Are you referring to libXNVCtrl.a? You can build it by changing to the src/libXNVCtrl directory and typing "make". You need your distribution's development packages for xlib and xext, at least. I'm not sure what else.

**Comment by aaronp24** [comment]
Did you ever get this resolved? If you still can't get this built, please provide more detail about the problem you're seeing.

**Comment by leaf918** [comment]
I have solved this problem,but without compiling the source code,I use ubuntu apt-get to install the xnvctrl-dev package.and it passed my test cases.
thanks very much.
