### ISSUE TITLE
SDI capture card data transfer to CUDA sample code.

### ISSUE THREAD

**Issue by leaf918** [NVIDIA/nvidia-settings#8]
hi,
I have read the entire book [quadro sdi capture programmer's guide],and read all the sample code in this repository.
is there a complete sample which can demostrate that transfer sdi frame data to cuda ,and processing the capture image .

**Comment by aaronp24** [comment]
Hi @leaf918,

I don't think a complete sample is available. Are the samples in [PG-03776-001_v05.pdf](http://international.download.nvidia.com/quadro/product-literature/programmers-guides/PG-03776-001_v05.pdf) insufficient?

nvidia-settings and the underlying NV-CONTROL extension are only concerned with querying and configuring the capture device. Actually capturing data is up to the [GL_NV_video_capture](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_video_capture.txt) extension, which is outside the scope of this repository.

Once your data is in OpenGL, I think you can use standard [GL/CUDA interop](http://docs.nvidia.com/cuda/cuda-samples/index.html#simple-opengl) methods to get it into CUDA.

**Comment by leaf918** [comment]
thanks very much.
I have read all the files and samples which you listed,I will spend a few days on this ,wish me lucky.
thanks again.
