### ISSUE TITLE
Consider move to libadwaita

### ISSUE THREAD

**Issue by nvidiaLinuxUser** [NVIDIA/nvidia-settings#90]
With all core GNOME apps, and many other GTK apps moving to libadwaita, nvidia-settings should consider moving to it as well. It will ensure the app does not look out of place with the rest of a user's system and provides many additional features.

**Comment by aaronp24** [comment]
How far back does libadwaita support go? We need to support the control panel on some -- let's say "vintage" -- distros.

**Comment by kbrenneman** [comment]
I haven't messed with it myself yet, but everything I've seen/read about libadwaita suggests that it's pretty closely tied to Gnome. Does libadwaita work well on non-Gnome environments, and if so, will it continue to work well? We don't want to add a new dependency just to have to rewrite everything again later to get rid of it.

With GTK, we can reasonably expect it to work well anywhere.

**Comment by nvidiaLinuxUser** [comment]
Okay thanks, I got it
