### ISSUE TITLE
Missing releases 515.86.01, 510.108.03, 470.161.03, 390.157

### ISSUE THREAD

**Issue by Kiskae** [NVIDIA/nvidia-settings#93]
As per https://forums.developer.nvidia.com/t/current-graphics-driver-releases/28500 there are 4 new official releases, but the tarballs for the related utilities are only found on the nvidia download mirror, not the github repositories.

Ping @aritger since he published the associated open-gpu-kernel release.

**Comment by aaronp24** [comment]
I usually take care of these on release day, but I was out of the office yesterday.
